// The words the site is written in, one set per language: what each label says, how a date is
// written, what each org is, and the paragraphs of the entry and the notes. Everything else in
// the content is measured from the repositories themselves.

const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

export const TEXT = {
  ja: {
    role: "言語と、その周りの道具をつくる",
    lead: "静的型付けの言語 Almide を書き、その言語で道具を書いています。",
    nameEn: "PUBLIC WORK",
    kicker: (n) => `公開リポジトリ ${n} 件`,
    description: (n) => `O6lvl4 と Aid-On、almide、almide-* の公開リポジトリ ${n} 件。言語 Almide とその周りの道具、エージェント、LLM の土台。`,
    note: (n) => `公開リポジトリ ${n} 件を並べた頁です。各プロジェクトの図版は、そのサイトの画面・コマンドの出力・README の要約から作りました。`,
    labels: {
      prev: "前のプロジェクト", next: "次のプロジェクト", index: "一覧", close: "閉じる", unit: "件",
      sortBy: "並べ替え", colNo: "No.", colTitle: "名前", colLead: "できること", colFormat: "言語", colDate: "更新",
      sort_date: "更新順", sort_commits: "コミット順", sort_format: "言語順", sort_name: "名前順",
      all: "すべて", object: "代表作", overview: "全体", points: "できること",
      topics: "話題", links: "行き先", output: "出力", unitShort: "リポジトリ", langsShort: "言語",
      language: "言語", sections: "この頁の節", theme: "配色", light: "明るく", dark: "暗く",
      skip: "本文へ", panel: "索引", status: "更新中",
      families: "系統", open: "開く", allFamilies: "系統の一覧へ",
      catalogue: "すべて", groups: "org", more: "順に見る", showMore: "残りを見る",
      about: "これまで", work: "仕事", orgs: "org", stack: "言語ごとのリポジトリ", history: "年表",
      byYear: "年ごとのコミット", byOrg: "org ごとのコミット", breakdown: "何を書いてきたか",
      allWorks: "全部を一覧で見る", home: "先頭の頁へ",
      briefLead: "系統ごとに、いちばん手を入れているものを一つずつ。残りは一覧で見られます。",
      listLead: "公開リポジトリの全件。系統と言語で絞り、更新日・コミット数・言語・名前で並べ替えられます。",
    },
    stats: { commits: "コミット", first: "初回", tag: "版", stars: "星" },
    links: { repo: "リポジトリ", site: "サイト" },
    figures: { repos: "公開リポジトリ", commits: "コミット", langs: "言語", years: "年", span: "期間" },
    panel: {
      handle: "名前", orgs: "org", first: "最初のコミット", last: "直近の更新",
      repos: "公開リポジトリ", commits: "コミット合計", house: "Almide で書いた割合",
      thisYear: (y) => `${y}年のコミット`,
    },
    stack: ["よく書く言語", "そのほか"],
    started: (n) => `${n}件を始めた`,
    andMore: (n) => ` ほか${n}件`,
    date: (iso) => `${iso.slice(0, 4)}年${Number(iso.slice(5, 7))}月`,
    orgs: {
      "O6lvl4": "手元の道具。コードを読む・測る・直すための小さな実行ファイルと、言語まわりの部品。",
      "almide": "Almide — 静的型付けの言語本体（Rust）と、仕様・文法・エディタ支援・実行環境。",
      "almide-graphics": "Almide で絵を描くための層。数学、描画時、UI、VRM/glTF、微分可能プログラミング。",
      "almide-ai": "Almide で書いたエージェント。CLI 実行環境、LLM クライアント、Mac を操作する手。",
      "almd-mc": "Almide で Minecraft のプロトコルを実装した一式。認証、チャンク、NBT、ボット。",
      "Aid-On": "Aid-On での仕事。LLM を使うための土台（流量制御、統一インターフェース、記憶、ストリーム）と AITuber の部品。",
    },
    about: () => [
      "静的型付けの言語 Almide をつくっています。言語本体は Rust で、仕様・文法・エディタ支援・実行環境を別のリポジトリに分けて置いています。",
      "その言語で道具を書きます。コードを構造で読む hew、構文木をつくる gramide、コードの質を測る codopsy、エージェントを閉じ込めて走らせる porta。どれも手元の作業で毎日使うものから始まっています。",
    ],
    aboutPage: {
      nav: "この頁について",
      description: "この頁の作り方と、収録の範囲。",
      sections: (total) => [
        { heading: "名前", text: '名は、雄弁と文字の神オグマ（Ogma）に由来します。石に刻んだ切り込みで綴るオガム文字を作った神です。頁の末尾に置いたのは、そのオガムで綴った <span class="cut">᚛ᚑᚌᚋᚐ᚜</span>（OGMA）で、碑文と同じく羽根印で前後を閉じています。節の見出しの刻みは、オガムが1本から5本で一字を数えるのに倣いました。' },
        { heading: "収録", text: `O6lvl4・Aid-On・almide・almide-graphics・almide-ai・almd-mc の公開リポジトリ ${total} 件（フォークを除く）。非公開のものは載せていません。` },
        { heading: "図版", text: "公開サイトのあるものはその画面、手元に入っているコマンドはその出力、それ以外は README の要約（何ができるか）です。要約は README の記述だけから作っています。" },
      ],
      footnote: "数値（コミット数・初回・言語）は手元の clone から測ったものです。コミットは著者日で数え、リポジトリ間で共有している履歴は一度だけ数えています（マージも1件として含みます）。",
    },
  },
  en: {
    role: "I build a language, and the tools around it",
    lead: "I write Almide, a statically-typed language, and write my own tools in it.",
    nameEn: "PUBLIC WORK",
    kicker: (n) => `${n} public repositories`,
    description: (n) => `${n} public repositories under O6lvl4, Aid-On, almide and the almide-* orgs: the Almide language, the tools around it, agents, and groundwork for LLMs.`,
    note: (n) => `${n} public repositories, side by side. Each plate is drawn from the project itself: its site as it renders, its command as it answers, or what its README says it does.`,
    labels: {
      prev: "Previous", next: "Next", index: "Index", close: "Close", unit: " repos",
      sortBy: "Sort", colNo: "No.", colTitle: "Name", colLead: "What it does", colFormat: "Language", colDate: "Updated",
      sort_date: "Recent", sort_commits: "Commits", sort_format: "Language", sort_name: "Name",
      all: "All", object: "One in full", overview: "Overview", points: "What it does",
      topics: "Topics", links: "Links", output: "Output", unitShort: "repos", langsShort: "langs",
      language: "Language", sections: "Page sections", theme: "Colour scheme", light: "Light", dark: "Dark",
      skip: "Skip to content", panel: "Profile · Index", status: "Active",
      families: "Families", open: "Open", allFamilies: "All families",
      catalogue: "All", groups: "Orgs", more: "See them one at a time", showMore: "Show the rest",
      about: "About", work: "Work", orgs: "Org", stack: "Repositories by language", history: "Timeline",
      byYear: "Commits by year", byOrg: "Commits by org", breakdown: "What I have written",
      allWorks: "See the whole list", home: "Front page",
      briefLead: "One from each family, the one most worked on. The rest are in the list.",
      listLead: "Every public repository. Narrow by family or language, order by date, commits, language or name.",
    },
    stats: { commits: "Commits", first: "Started", tag: "Release", stars: "Stars" },
    links: { repo: "Repository", site: "Site" },
    figures: { repos: "Repositories", commits: "Commits", langs: "Languages", years: "Years", span: "Span" },
    panel: {
      handle: "Handle", orgs: "Orgs", first: "First commit", last: "Last touched",
      repos: "Public repos", commits: "Commits total", house: "Written in Almide",
      thisYear: (y) => `Commits in ${y}`,
    },
    stack: ["Most written", "Also"],
    started: (n) => `${n} started`,
    andMore: (n) => ` and ${n} more`,
    date: (iso) => `${MONTHS[Number(iso.slice(5, 7)) - 1]} ${iso.slice(0, 4)}`,
    orgs: {
      "O6lvl4": "The tools at hand: small binaries for reading, measuring and fixing code, and the parts of a language toolchain.",
      "almide": "Almide — the statically-typed language itself (in Rust), with its specification, grammar, editor support and runtimes.",
      "almide-graphics": "The layer for drawing in Almide: maths, a graphics runtime, UI, VRM/glTF, and differentiable programming.",
      "almide-ai": "Agents written in Almide: a CLI runtime, an LLM client, and a hand that works a Mac.",
      "almd-mc": "Minecraft's protocol implemented in Almide: authentication, chunks, NBT, and a bot.",
      "Aid-On": "Work at Aid-On: groundwork for using LLMs (rate limiting, one interface, memory, streams) and the parts of an AITuber.",
    },
    about: () => [
      "I build Almide, a statically-typed language. The compiler is written in Rust; its specification, grammar, editor support and runtimes each live in their own repository.",
      "Then I write my tools in it: hew reads code by structure, gramide builds syntax trees, codopsy measures code quality, porta runs agents inside a sandbox. Each one started as something I needed that day.",
    ],
    aboutPage: {
      nav: "About this page",
      description: "How this page is built, and what it covers.",
      sections: (total) => [
        { heading: "The name", text: 'The name comes from Ogma, the god of eloquence and writing, credited with ogham — an alphabet spelled as notches cut along a stem. The mark that closes the page is that name cut in ogham, <span class="cut">᚛ᚑᚌᚋᚐ᚜</span> (OGMA), between the feather marks an inscription opens and closes with; the notches that open each section count from one to five, the way ogham counts a letter.' },
        { heading: "Covers", text: `${total} public repositories under O6lvl4, Aid-On, almide, almide-graphics, almide-ai and almd-mc, forks excluded. Nothing private is shown.` },
        { heading: "Plates", text: "Projects with a site of their own show that site as it renders; projects whose command is installed here show its real output; the rest show a summary of what their README says they do, taken only from the README." },
      ],
      footnote: "The figures — commits, first commit, languages — are measured from the clones. Commits are counted by author date, history shared between repositories is counted once, and a merge counts as one commit.",
    },
  },
  zh: {
    role: "做一门语言，以及它周围的工具",
    lead: "我写静态类型语言 Almide，并用它写自己的工具。",
    nameEn: "PUBLIC WORK",
    kicker: (n) => `公开仓库 ${n} 个`,
    description: (n) => `O6lvl4、Aid-On、almide 与 almide-* 组织下的 ${n} 个公开仓库：Almide 语言、周边工具、智能体，以及 LLM 的基础设施。`,
    note: (n) => `这一页并列了 ${n} 个公开仓库。每个图版都取自项目本身：站点的画面、命令的输出，或 README 的摘要。`,
    labels: {
      prev: "上一个", next: "下一个", index: "总览", close: "关闭", unit: " 个",
      sortBy: "排序", colNo: "No.", colTitle: "名称", colLead: "功能", colFormat: "语言", colDate: "更新",
      sort_date: "按更新", sort_commits: "按提交", sort_format: "按语言", sort_name: "按名称",
      all: "全部", object: "详看一件", overview: "总体", points: "功能",
      topics: "话题", links: "去处", output: "输出", unitShort: "仓库", langsShort: "语言",
      language: "语言", sections: "本页各节", theme: "配色", light: "浅色", dark: "深色",
      skip: "跳到正文", panel: "索引", status: "更新中",
      families: "系列", open: "打开", allFamilies: "全部系列",
      catalogue: "全部", groups: "组织", more: "逐一浏览", showMore: "显示其余",
      about: "关于", work: "作品", orgs: "org", stack: "各语言的仓库数", history: "年表",
      byYear: "各年提交", byOrg: "各 org 的提交", breakdown: "写过些什么",
      allWorks: "查看完整列表", home: "回到首页",
      briefLead: "每个系列各取一个：最常动手的那个。其余都在列表里。",
      listLead: "全部公开仓库。可按系列与语言筛选，按更新日期、提交数、语言或名称排序。",
    },
    stats: { commits: "提交", first: "首次", tag: "版本", stars: "星标" },
    links: { repo: "仓库", site: "站点" },
    figures: { repos: "公开仓库", commits: "提交", langs: "语言", years: "年数", span: "年份" },
    panel: {
      handle: "名号", orgs: "组织", first: "首次提交", last: "最近更新",
      repos: "公开仓库", commits: "提交总数", house: "用 Almide 写的比例",
      thisYear: (y) => `${y} 年的提交`,
    },
    stack: ["常写的语言", "其他"],
    started: (n) => `开始了 ${n} 个`,
    andMore: (n) => ` 等 ${n} 个`,
    date: (iso) => `${iso.slice(0, 4)}年${Number(iso.slice(5, 7))}月`,
    orgs: {
      "O6lvl4": "手边的工具：读代码、量代码、改代码的小程序，以及语言工具链的零件。",
      "almide": "Almide — 静态类型语言本体（Rust），及其规范、语法、编辑器支持与运行时。",
      "almide-graphics": "用 Almide 作画的一层：数学、绘图运行时、UI、VRM/glTF、可微编程。",
      "almide-ai": "用 Almide 写的智能体：CLI 运行时、LLM 客户端，以及操作 Mac 的手。",
      "almd-mc": "用 Almide 实现的 Minecraft 协议：认证、区块、NBT 与机器人。",
      "Aid-On": "在 Aid-On 的工作：使用 LLM 的基础设施（限流、统一接口、记忆、流）与 AITuber 的零件。",
    },
    about: () => [
      "我在做静态类型语言 Almide。编译器用 Rust 写，规范、语法、编辑器支持与运行时各自放在独立的仓库。",
      "然后用它写工具：按结构读代码的 hew、构建语法树的 gramide、衡量代码质量的 codopsy、把智能体关进沙箱运行的 porta。每一个都从当天需要的东西开始。",
    ],
    aboutPage: {
      nav: "关于本页",
      description: "本页的做法与收录范围。",
      sections: (total) => [
        { heading: "名字", text: '名字取自雄辩与文字之神奥格玛（Ogma），相传欧甘文字由他所创——以刻在竖线上的刻痕拼写。页面末尾的那个记号就是用欧甘文刻的 <span class="cut">᚛ᚑᚌᚋᚐ᚜</span>（OGMA），两端以碑文起止的羽状符号收束；每节标题前的刻痕以一至五道计数，与欧甘记一个字母的方式相同。' },
        { heading: "收录", text: `O6lvl4、Aid-On、almide、almide-graphics、almide-ai、almd-mc 的 ${total} 个公开仓库（不含 fork）。不公开的仓库不在此列。` },
        { heading: "图版", text: "有独立站点的，用站点画面；本机装有命令的，用命令的真实输出；其余用 README 的摘要（能做什么）。摘要只依据 README。" },
      ],
      footnote: "提交数、首次提交、语言等数字，均由本地克隆测得。提交按作者日期计数，仓库之间共享的历史只计一次，合并提交计为一次。",
    },
  },
};
